name: Build and test

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
      GOLANG_VERSION: 1.17.11
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GOLANG_VERSION }}
        check-latest: false

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...

    - name: Install gotestsum
      run: go install gotest.tools/gotestsum@latest

    - name: Run tests
      run: gotestsum --no-color=false -- -race -coverprofile=cover.out -covermode=atomic -vet=off ./...

    - name: Quality Gate
      run: |
        total=`go tool cover -func=cover.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
        echo "Total test coverage = $total%"
        if (( $(echo "$total 75" | awk '{print ($1 < $2)}') )); then
          echo "Quality gate failed. Coverage below minimum 75%"
          exit 1
        fi

